-
  name: Test connection to a server and then stop apache2 service running
  hosts: web_nodes
  gather_facts: false
  tasks:
    -
      name: Uninstall the apache on the remote host
      package:
          name: apache2
          state: absent
